spring.application.name=demo
server.port=8081

# MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/studytracker

# Optional (logs dekhne ke liye helpful)
spring.data.mongodb.auto-index-creation=true